use crate::backend::IBackendConfig;
use crate::backend::arguments::ArgumentError;
use crate::backend::arguments::parse_bool;

#[derive(Default)]
pub struct Config {
    pub generate_cargo_toml: bool,
}

impl IBackendConfig for Config {
    fn parse_arguments(
        args: impl Iterator<Item = (String, String)>,
    ) -> Result<Self, ArgumentError> {
        let mut config = Self::default();
        for (arg, val) in args {
            match arg.as_str() {
                "generate_cargo_toml" => parse_bool(&arg, &val, &mut config.generate_cargo_toml)?,
                _ => return Err(ArgumentError::UnsupportedArgument { argument: arg }),
            }
        }
        Ok(config)
    }
}
impl Config {
    pub const SHARED_MODEL_CRATE_URL: &str = r"https://github.com/matter-labs/zksync-error";
    pub const PREAMBLE: &'static str =
        "AUTOGENERATED BASED ON A SET OF JSON FILES, DO NOT EDIT MANUALLY";
}
