[book]
authors = [
    "Igor Zhirkov",
    "Matter Labs"
]
language = "en"
multilingual = false
src = "src"
title = "ZKsync error crate documentation"

[output.html]
additional-js = ["js/version-box.js"]
additional-css = ["css/version-box.css"]
